### ISSUE TITLE
Freeze when running colcon build on Raspberry Pi

### ISSUE THREAD

**Issue by Tsuji-Kosei** [DDTRobot/diablo_ros2#5]
Hi!
I am trying to build "basic" branch code on raspberry pi 4 model B (on diablo robot) but it freezes halfway through.
First I tried running 
`$ colcon build `
but it froze while "diablo_body:build 80%" was displayed.
Next, to solve the out of memory problem, I tried running
```
$ MAKEFLAGS="-j1 -l1"
$ colcon build --executor sequential
```
but the results did not change.
I would like to know if you have any solutions.

Thank you.

**Comment by YimingShu-teay** [comment]
I have the issue! Could you tell me how you solve the problem

**Comment by Tsuji-Kosei** [comment]
Hi, It was probably due to lack of memory and I confirmed that it could be built using an Raspberry pi model 4b 8G RAM.

**Comment by stanleylim24** [comment]
Hi, I am facing the same issue. My Diablo robot is using Raspberry Pi 4 too, could I check how did you resolve the problem? Did you have to upgrade the RAM or replace the raspberry pi with another one that has a larger RAM?
